### Dependencies

##Backups

#Backup del cuaderno hasta dia 20/07/2023
backup1 = [['hello','안녕하세요','annyeonghaseyo'],['goodbye','안녕','annyeong'],['nice to meet you','만나서 방갑습니다','mannaseo bangabseobnida'],['monday','월요일','woryoil'],['tuesday','화요일','hwayoil'],
           ['wednesday','수요일','suyoil'],['thursday','목요일','mogyoil'],['friday','금요일','geumyoil'],['saturday','토요일','toyoil'],['sunday','일요일','iryoil'],['day','하루','haru'],
           ['how','어떻게','eotteohge'],['what','무엇울','mueoseul'],['when','언제','eonje'],['where','어디서','eodiseo'],['which','어느것을','eoneugeoseul'],
           ['who','누구를','nugureul'],['why','왜','wae'],['how much','얼마나 오래','eolmana orae'],['how many','얼마나 많이','eolmana manhi'],
           ['I','나는','naneun'],['you','너','neo'],['he','그','geu'],['she','그녀','geunyeo'],['we','우리','uri'],
           ['you','당신','dangsindeul'],['they','그들','geudeul'],['1','하나','hana'],['2','둘','dul'],['3','셋','set'],
           ['4','넷','net'],['5','다섯','daseot'],['6','여섯','yeoseot'],['7','일곱','ilgob'],['8','여덟','yeodeolb'],
           ['9','아홉','ahob'],['10','열','yeol'],['1','일','il'],['2','이','i'],['3','삼','sam'],
           ['4','사','sa'],['5','오','o'],['6','육','yuk'],['7','칠','chil'],['8','팔','pal'],
           ['9','구','gu'],['10','십','sib'],['100','백','baek'],['1000','천','cheon'],['10000','만','man'],
           ['time','시간','sigan'],['hour','시','si'],['minute','분','bun'],['excuse me','칠례합니다','chillyehabnida'],['sorry','미안에요','mianeyo'],
           ['excuse me','저기요','jeogiyo'],['thank you','고맙습니다','gomabseubnida'],['thanks','감사합니다','gamsahabnida'],['im sorry','최송합니다','choesonghabnida'],['im okay','괜찮습니다','gwenchanhseubnida'],
           ['please','제발','jebal'],['one moment','잠깐만요','jamkkanmanyo'],['food','음식','eumsik'],['drink','음료','eumryo'],['apple','사과','sagwa'],
           ['cool','맛있는','masissneun'],['tasty','맛있어요','masisseoyo'],['chicken','닭','dalk'],['taste','맛','mas'],['rice','밥','bab'],
           ['restaurant','식당','sikdang'],['not tasty','맛없어요','maseobseoyo'],['ramen','라면','ramyeon'],['tea','차','cha'],['water','물','mul'],
           ['vegetable','야채','yachae'],['fruit','과일','gwail'],['soup','수프','supeu'],
           ['beer','맥주','maegju'],['strawberry','딸기','ddalgi'],['hamburguer','햄버가','haembeoga'],
           ['fish','생선','saengseon'],['egg','계람','gyeram'],
           ['week','한주','hanju'],['weekend','주말','jumal'],['month','달','dal'],['year','해','hae'],
           ['movie','영화','yeonghwa'],['fox','여우','yeou'],['small','작','jak'],['big','크','keu'],['trash','쓰레기','sseuregi'],
           ['flower','곷','goj'],['entrance','입고','ibgo'],['name','이름','ireum'],['ant','개미','gaemi'],['lately','요즘','yojeum'],
           ['crow','까마괴','ggamagwi'],['star','결','gyeol'],['leaf','잎','ip'],['kiss','뽀뽀','ppoppo'],['outside','밭','bat'],
           ['daytime','낮','naj'],['child','아이','ai'],['today','이를','ireul'],['last name','성 은','seong eun'],['story','이야기','iyagi'],
           ['slow','느립','neurib'],['fast','빠릅','ppareub'],['woman','여자','yeoja'],['man','남자','namja'],['now','지금','jigeum'],
           ['cat','고양이','goyangi'],['dog','개','gae'],['book','책','chaek'],['ball','공이','gongi'],['China','중국','jungguk'],
           ['Japan','일본','ilbon'],['EEUU','미국','miguk'],['Britain','영국','yeongguk'],['Thailand','태국','taeguk'],['Australia','호주','hoju'],
           ['Egypt','이집트인','ijipteuin'],['South Africa','나마곤','namagon'],['Germany','도길','dogil'],['teacher','선생님','seonsaengnim'],['doctor','의사','uisa'],
           ['office worker','회사원이','hwisaweoni'],['police','견찰','gyeonchal'],['singer','가수','gasu'],['actor','배우','baeu'],['home','집','jib'],
           ['school','학교','hakgyo'],['class','교실','gyosil'],['toguether','같이','gati'],['company','회사','hwisa'],['market','시장','sijang'],
           ['hospital','병원','byeongwon'],['customer','손님','sonnim'],['line','줄','jul'],['interest','재미','jaemi'],['desk','책상','chaeksang'],
           ['bench','벤치','benchi'],['mountain','산','san'],['island','섬','seom'],['park','공원','gongwon'],['room','방','bang'],
           ['sea','바다','bada'],['tree','나무','namu'],['butterfly','나비','nabi'],['floor','바닥','batak'],['chair','의자','uija'],
           ['bag','가방','gabang'],['car','차동자','chadongja'],['library','도서광','doseogwan'],['table','탁자','takja'],['bed','침대','chimdae'],
           ['road','길','gil'],['street','길에','gile'],['a little','조금','jogeum'],['post office','우제국','ujeguk'],['university','대학교','daehakgyo'],
           ['thing','물건','mulgeon'],['this','이게','ige'],['this','구것은','geugeoseun'],
           ['that','저','jeo'],['here','여기','yeogi'],['there','저기는','jeogineun'],['thats all for today','오늘은 여기까지','oneuleun yeogikkaji'],
           ['safeness','안전','anjeon'],['sickness','아픕','apeub'],['sincerity','성실','seongsil'],['honesty','솔직','soljik'],
           ['tough','튼튼','teunteun'],['clean','깨끗','kkaekkeus'],['attractive','매력적인','maereokjeokin'],['kindness','친절','chinjeol'],['pretty','예쁩','yeppeub'],
           ['selfishness','이기적','igijeok'],['nice','착','chak'],['smart','똑똑','ttokttok'],
           ['if','만약','manyak'],['althought','하더라도','hadeorado'],
           ['maybe','아마','ama'],['therefore','그러니까','geureonikka'],['for example','예를 들면','yereul deulmyeon'],['by the way','그런데','geureonde'],['then','그럼','geureom'],
           ['so','이렇게','ireohge'],['finally','최종적으로','choejongjeokeuro'],['at least','적어도','jeokeodo'],['also','그리고','geurigo'],['or','또는','ttoneun'],
           ['because','때무네','ttaemune'],['but','하지만','hajiman'],['many','많이','manhi'],['not many','조금','jo geum'],['some','이부','ilbu'],
           ['all of it','모든 것','modeun geos'],['all of them','모든 사람','modeun saram'],['except','제외하고','jeoehago'],['during','동안','dongan'],['in','에','e'],
           ['my','나의','naui'],['your','당신의','dangsinui'],['his','그의','geuui'],['her','그녜의','geunyeoui'],['our','우리의','uriui'],
           ['their','그들의','geudeului'],['these','이것들','igeosdeul'],['those','제것들','jeogeosdeul'],['with','함께','hamkke'],['without','없이','eobsi'],
           ['letter','편지','pyeonji'],['bookstore','서점','seojeom'],['article','기사를','gisareul'],['pool','수전장','sujeonjang'],
           ['academy','학원','hakwon'],['dormitory','기숙사','gisuksa'],['study room','촉서실','chokseosil'],['lobby','로비로','lobiro'],['order','순서','sunseo'],
           ['building','근물','geonmul'],['language','언어','eoneo'],['word','단어','daneo'],
           ['thought','생각','saenggak'],['dialogue','대화','daehwa'],['am i right','제 마리 맞습니다','je mari majseubnida'],['everyday','마일','maeil'],
           ['weather','계절','gyejeol'],['winter','계울','gyeul'],['summer','여름','yeoreum'],['spring','봄','bom'],['autumn','가을','gaeul'],
           ['cloudy','흐립니다','heuribnida'],['wet','습합니다','seubhabnida'],['is raining','비가 옵니다','biga opnida'],['is snowing','눈이 옵니다','nuni opnida'],['is windy','바람이 붑니다','barami bubnida'],
           ['whats the weather like','날씨가 어떻 습니다','nalssiga eotteoh seubnida'],['good weather','주흔 날씨','juheun nalssi'],['bad weather','구흔 날씨','guheun nalssi'],['whats the temperature','기온이 어떻게 됩니까','gioni eoteohge doebbnikka'],['degree','도야','doya'],
           ['mother','어머니','eomeoni'],['father','아버지','abeoji'],['brother','현제','hyeonje'],['sister','자매','jamae'],['son','아들','adeul'],
           ['daughter','딸','ttal'],['boy','아이','ai'],['parents','부모','bumo'],['father in law','의붓 아버지','uibut abeoji'],['mother in law','의붓 어머니','uibut eomeoni'],
           ['brother in law','이복 현제','ibok hyeonje'],['sister in law','이복 자매','ibok jamae'],['wife','아내','anae'],['husband','남편','nampyeon'],['son in law','사미','sami'],
           ['daughter in law','면느리','myeonneuri'],['grandson','손자','sonja'],['granddaughter','손녀','sonnyeo'],['grandfather','하라버지','harabeoji'],['grandmother','할머니','halmeoni'],
           ['grandparents','조부모','jobumo'],['grandsons','손주들','sonjudeul'],['aunt','이모','imo'],['uncle','숙부','sukbu'],['nephew','남자 조카','namja joka'],
           ['niece','여자 조카','yeoja joka'],['cousin','사촌형제','sachonhyeongje'],['blouse','불라우스','bullauseu'],['dress','원피스','wonpiseu'],['short pants','반바지','banbaji'],
           ['long pants','바지','baji'],['skirt','스키트','seukiteu'],['shirt','셔츠','syeocheu'],['bag','지갑','jigap'],['jeans','천바지','cheonbaji'],
           ['sport tights','제깅스','jegingseu'],['belt','벨트','belteu'],['tie','넥타이','nektai'],['warmer','코트','koteu'],['jacket','재킷','jaekis'],
           ['sweater','스웨터','seuweteo'],['oilskin','우비','ubi'],['scarf','스카프','seukapeu'],['gloves','장갑','janggap'],['hat','모자','moja'],
           ['umbrella','우산','usan'],['botes','부츠','bucheu'],['sandals','샌들','saendeul'],['bra','브래지어','beuraejieo'],['socks','양말','yangmal'],
           ['tights','스타킹','seutaking'],['pijama','자못','jamos'],['leotards','타이즈','taijeu'],['shoes','슬리퍼','seullipeo'],['gawn','가운','gaun'],
           ['undershirt','속옷 상의','sogot sangui']]

#Backup de verbos hasta dia 02/11/2023
backup2 = [['write','적스다','jeokseuda'],['read','읽스다','ilkseuda'],['talk','말하다','malhada'],['study','공부하다','gongbuhada'],['tell','이야기하다','iyagihada'],['think','생각하다','saenggakhada'],['converse','대화하다','daehwahada'],
           ['do','하다','hada'],['meet','만나다','mannada'],['watch','보다','boda'],['born','태어나다','taeeonada'],['graduate','졸업하다','joleobhada'],['listen','들다','deulda'],['marry','결혼하다','gyeolhonhada'],['eat','먹다','meokda'],['drink','마시다','masida'],
           ['buy','사다','sada'],['sell','파다','pada'],['work','일하다','ilhada'],['sleep','자하다','jahada'],['have','있다','issda'],['not have','없다','eobsda'],['greet','인사테리다','insaterida'],['call','천화하다','cheonhwahada'],['be from','사람이다','saramida'],
           ['go','가다','gada'],['national of','출신이다','chulsinida'],['come','오다','oda'],['ride','타다','tada'],['return','동아가다','dongagada'],['walk','걱다','geokda'],['clean','청소하다','cheongsohada'],['run','달리다','dallida'],['sit','앉다','anjda'],
           ['stand','서다','seoda'],['lie on','눕다','nubda'],['swim','수영하다','suyeonghada'],['wait','기다리다','gidarida'],['learn','배우다','baeuda'],['sing','부르다','bureuda'],['want','싶다','sipda'],['can','돼다','dwaeda'],['answer','받다','badda'],
           ['live','살다','salda'],['smoke','피우다','piuda'],['being far','멀다','meolda'],['being close','가까우다','gakkauda'],['being able','몾다','mojda'],['relax','쉬다','swida'],['play','치다','chida'],['look for','찾다','chajda'],['know','알다','arda'],
           ['not know','모르다','moleuda'],['like','촣아하다','chohahada'],['dislike','싫어하다','silheohada'],['be','이다','ida'],['die','죽다','jukda'],['use','쓰다','sseuda'],['dance','추다','chuda'],['give','주다','juda'],['turn on','겨다','gyeoda'],['count','세다','seda'],['being small','작다','jakda'],
           ['being big','크다','keuda'],['being hard','힘들다','himdeulda'],['being better','낫다','nasda'],['wear','입다','ibda'],['put','놓다','nohda'],['being like this','그렿다','geureohda'],['start','시작하다','sijakhada'],
           ['being mine','제것이다','jegeosida'],['being hurt','아픕다','apeubda'],['being safe','안전다','anjeonda'],['being pretty','예쁘다','yeppeuda'],['being sincere','성실다','seongsilda'],['being cute','귀엽다','guiyeobda'],['being clean','깨끗하다','kkaekkeushada'],
           ['being dirty','더겁다','deogeobda'],['being thin','날씬하다','nalssinhada'],['being fat','뚱뚱하다','ddungddunghada'],['teach','가르치다','gareuchida'],['get right','맞다','majda'],['being tall','높다','nopda'],['being short','작다','jakda'],
           ['being busy','바쁘다','babbeuda'],['being cold','춥다','chubda'],['being hot','덥다','deobda'],['be from','출신이다','chulsinida'],['being light','가볍다','gabyeobda'],['being heavy','무접다','mujeobda'],['have much','많다','manhda'],
           ['being happy','행복하다','haegbokhada'],['being tired','피공하다','pigonghada'],['cook','요리하다','yorihada'],['being rare','이상하다','isanghada'],['being quiet','주용하다','juyonghada'],['ship','부지다','bujida'],['ask','묻다','mudda'],
           ['present','선물하다','seonmulhada'],['throw','덜지다','deoljida'],['go up','을라가다','eulragada'],['go down','내려가다','naeryeogada'],['arrive','드착하다','deuchakhada'],['thank','고맙다','gomabda'],['attend','다니다','danida'],
           ['become','되다','dwida'],['laugh','웃','usda'],['cry','울','ulda'],['turn around','뒤다','duida'],['being short','키가 작다','kiga jakda'],['being tall','키가 크다','kiga keuda'],['being brave','용감하다','yonggamhada'],['being lazy','게으르다','geeureuda'],['being easy','쉽스다','suibseuda'],
           ['being hard','어렵다','eoryeobda'],['being healthy','튼튼하다','teunteunhada'],['being confortable','펀하다','peonhada'],['open','열다','yeolda'],['being nice','촣다','chohda'],['being awfull','싫다','silhda'],['being amazing','대단하다','daedanhada'],['being wrong','들리다','teullida'],
           ['being interesting','재미있다','jaemiissda'],['being boring','재미없다','jaemieobsda'],['go out','나가다','nagada'],['come out','나오다','naoda'],['come here','돌아오다','dolaoda'],['come there','돌아가다','dolagada'],['explain','설명하다','seolmyeonghada'],['respond','대답하다','daedabhada'],
           ['repeat','따라하다','ttalahada'],['understand','이해하다','ihaehada'],['being cheap','싸다','ssada'],['being expensive','비싸다','bissada'],['being illuminated','밝다','balkda'],['arrive','도착하다','dochakhada'],['go inside','들어가다','deuleogada'],['come inside','들어오다','deuleooda'],
           ['being clear','맑다','malkda'],['being kind','친절하다','chinjeolhada'],['travel','여행하다','yeohaenghada'],['take a walk','산책하다','sanchekhada']]